@include("appointment.partials.layer-fields.type")
@include("appointment.partials.layer-fields.location_id")
@include("appointment.partials.layer-fields.description")
@include("appointment.partials.layer-fields.user_id")
@include("appointment.partials.layer-fields.dates")
@include("appointment.partials.layer-fields.buttons")